image:
  file: gitpod.Dockerfile
tasks:
  - init: |
      apt-get update
      apt-get install -yq ffmpeg
  - init: poetry install
  - command: uvicorn songolo:app --host 0.0.0.0 --port 8080 --reload
ports:
  - port: 8080
    onOpen: ignore
    visibility: public
