tasks:
  - init: |
      python -m pip install poetry
      python -m poetry lock
      python -m poetry update
      python -m poetry install
      sudo apt-get install ffmpeg
    command: |
      python -m poetry run uvicorn songolo:app --host 0.0.0.0 --port 8080 --reload