tasks:
  - before: |
      sudo apt-get install ffmpeg -yq
      pip install poetry
      poetry install
  - command: uvicorn songolo:app --host 0.0.0.0 --port 8080 --reload
ports:
  - port: 8080
    onOpen: ignore
    visibility: public